### ISSUE TITLE
Use SonarQube for code analysis

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/VaraniumSharp.WinUI#1]
# Description
Update CakeScripts and make use of SonarQube for code analysis.

# Tasks
- [x] Set up SonarCloud project
- [x] Update build scripts
- [x] Update AppVeyor.yaml
- [x] Update readme to show SonarCloud badges
