### ISSUE TITLE
Setting Page

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/VaraniumSharp.WinUI#11]
# Description
Add a setting page that the user can control by implementing an interface which will automatically add setting panes to the appropriate tab.
The pane should be openable from the main flyout menu.

# Tasks
- [x] Add main setting page
- [x] Add interface that setting classes should implement
- [x] Add logic to load and populate settings
