### ISSUE TITLE
Create sort control

### ISSUE THREAD

**Issue by DeadlyEmbrace** [NinetailLabs/VaraniumSharp.WinUI#16]
# Description
Port the sorting UI and logic from ACM-NG to WinUI.
Control should show sort option as a collection of items each with an arrow for ascending and descending with a second list to drag the items to for the sort.
Overall the logic from NG should be fine with some minor tweaks to accommodate the new control scheme and WinUI specifics.

# Tasks
- [x] Port sorting attribute
- [x] Port sorting logic
- [x] Create user control for sorting
  - [x] Add button to clear the sort
  - [x] Abstract drag/drop logic and make it work both direction
  - [x] Create user control containing the sort controls
- [x]  Add logic to persist the sort settings (this should hook into the loading of tab, but also have general events others can use if required)
  - [x] Update sort control to allow auto-reloading of persisted setting (if it exists)
  - [x] Add abstract class for sortable display components that auto load previous sort
  - [x] Hook up with loading logic
- [x]  Add unique Id for each control so sort entries can be correctly identified (currently there is a risk of getting the wrong one if multiple controls of the same type are in a view)
- [x] Sonar cleanup
- [x] Code cleanup with ReSharper (which isn't working in VS2022 for some reason since the full release)
